import { Weather } from "./weather.interface";

export const initialWeather: Weather = {
    //SECTION 0
    miMi: 'AA',
    mjMj: 'XX',
    // estacao: '',
    ddddddd: '',
    a1: '',
    bw: '',
    nbNbNb: '',
    yy: '',
    gg: '',
    iw: '',
    ii: '',
    iii: '',
    laLaLa: '',
    qc: '',
    loLoLoLo: '',
    //SECTION 1
    ir: '',
    ix: '',
    h: '',
    vv: '',
    n: '',
    dd: '',
    ff: '',
    fff: '',
    sn1_1: '',
    ttt: '',
    sn2_1: '',
    tdTdTd: '',
    poPoPoPo: '',
    pppp: '',
    a3: '',
    hhh: '',
    a: '',
    ppp: '',
    rrr: '',
    tr: '',
    ww: '',
    w1W2: '',
    // w1: '',
    // w2: '',
    waWa: '',
    wa1: '',
    wa2: '',
    nh: '',
    cl: '',
    cm: '',
    ch: '',
    gggg: '',
    //SECTION 2
    ds: '',
    vs: '',
    ss: '',
    twTwTw: '',
    pwaPwa: '',
    hwaHwa: '',
    pwPw: '',
    hwHw: '',
    dw1Dw1: '',
    dw2Dw2: '',
    pw1Pw1: '',
    hw1Hw1: '',
    pw2Pw2: '',
    hw2Hw2: '',
    is_ice: '',
    eses: '',
    rs: '',
    hwaHwaHwa: '',
    sw: '',
    tbTbTb: '',
    ci: '',
    si: '',
    bi: '',
    di: '',
    zi: '',
    //SECTION 3
    sn1_3: '',
    txTxTx: '',
    sn2_3: '',
    tnTnTn: '',
    ind89: '',
    p24P24P24: '',
    //SECTION 5
    iChw: '',
    iCm: '',
    cs: '',
    iCf: '',
    iCp: '',
    iCq: '',

    dataObservacao: new Date(),
    dateObservation: new Date(),
    observador: '',
    observerName: '',

    station: undefined,
    observer: undefined,
}