import { Food } from './food.interface';

export const initialFood : Food = {
	id: '',
	ibgeCode: '',
	name: '',
	preparation: 0,
	energy: 0,
	protein: 0,
	totalLipids: 0,
	carbohydrate: 0,
	fiber: 0,
	cholesterol: 0,
	saturated: 0,
	monounsaturated: 0,
	polyunsaturated: 0,
	linoleic: 0,
	linolenic: 0,
	trans: 0,
	totalSugar: 0,
	addedSugar: 0,
	calcium: 0,
	magnesium: 0,
	manganese: 0,
	phosphorus: 0,
	iron: 0,
	sodium: 0,
	addedSodium: 0,
	potassium: 0,
	copper: 0,
	zinc: 0,
	selenium: 0,
	retinol: 0,
	vitaminaA: 0,
	tiamina: 0,
	riboflavina: 0,
	niacina: 0,
	niacinaNE: 0,
	piridoxina: 0,
	cobalamina: 0,
	folato: 0,
	vitaminaD: 0,
	vitaminaE: 0,
	vitaminaC: 0
}