export const vector: string[][] = [
    // ["userEntity", "people-circle", "first"],
    // ["role", "calendar3", "second"],
    // ["food", "toggles2", "third"],
    // ["food_category", "table", "fourth"],
    // ["military", "chat-quote-fill", "fifth"],
    // ["composite_unit", "collection", "sixth"],
    ["weather", "table", "sixth"],
    // ["weatherOffShore", "home", "sixth"],
    // ["weatherOnShore", "speedometer2", "sixth"],
    // ["weatherHistoric", "bootstrap", "weatherHistoric"],
    // ["weatherHistoricOffShore", "table", "weatherHistoricOffShore"],
    // ["weatherHistoricOnShore", "geo-fill", "weatherHistoricOnShore"],
    // ["commission", "collection", "sixth"],
    // ["country", "cpu-fill", "sixth"],
    // ["equipment", "people-circle", "sixth"],
    // ["harbor", "grid", "sixth"],
    // ["institution", "collection", "sixth"],
    // ["manufacturer", "collection", "sixth"],
    // ["observer", "collection", "sixth"],
    // ["om", "collection", "sixth"],
    // ["platform", "calendar3", "sixth"],
    // ["platform_category", "chat-quote-fill", "sixth"],
    // ["researcher", "collection", "sixth"],
    // ["station", "chm", "sixth"],
    // ["stationCategory", "gear-fill", "sixth"],
    // ["station_historic", "cpu-fill", "sixth"],
    // ["stationOffShore", "speedometer", "sixth"],
    // ["stationOnShore", "toggles2", "sixth"],
    // ["surveying", "collection", "sixth"],
    // ["user", "grid", "sixth"],
    // ["tooltip role", "chevron-right", "sixth"]
]