import { initialObserver } from "../observer/observer.initial";
import { initialStation } from "../station/station.initial";
import { WeatherOnShore } from "./weather.on.shore.interface";

export const initialWeatherOnShore: WeatherOnShore = {
    //SECTION 0
    aabbxx: '',
    mimi: '',
    mjmj: 'XX',
    estacao: '',
    ddddddd: '',
    a1: '',
    bw: '',
    nbnbnb: '',
    yy: '',
    gg: '',
    iw: '',
    ii: '',
    iii: '',
    lalala: '',
    qc: '',
    lolololo: '',
    //SECTION 1
    ir: '',
    ix: '',
    h: '',
    vv: '',
    n: '',
    dd: '',
    ff: '',
    fff: '',
    sn1_1: '',
    ttt: '',
    sn2_1: '',
    tdtdtd: '',
    p0p0p0p0: '',
    pppp: '',
    a3: '',
    hhh: '',
    a: '',
    ppp: '',
    rrr: '',
    tr: '',
    ww: '',
    w1w2: '',
    // w1: '',
    // w2: '',
    wawa: '',
    wa1: '',
    wa2: '',
    nh: '',
    cl: '',
    cm: '',
    ch: '',
    gggg: '',
    //SECTION 2
    ds: '',
    vs: '',
    ss: '',
    twtwtw: '',
    pwapwa: '',
    hwahwa: '',
    pwpw: '',
    hwhw: '',
    dw1dw1: '',
    dw2dw2: '',
    pw1pw1: '',
    hw1hw1: '',
    pw2pw2: '',
    hw2hw2: '',
    is_ice: '',
    eses: '',
    rs: '',
    hwahwahwa: '',
    sw: '',
    tbtbtb: '',
    ci: '',
    si: '',
    bi: '',
    di: '',
    zi: '',
    //SECTION 3
    sn1_3: '',
    txtxtx: '',
    sn2_3: '',
    tntntn: '',
    ind89: '',
    p24p24p24: '',
    //SECTION 5
    ichw: '',
    icm: '',
    cs: '',
    icf: '',
    icp: '',
    icq: '',

    dataObservacao: new Date(),
    dateObservation: new Date(),
    observador: '',
    observerName: '',

    station: initialStation,
    observer: initialObserver,
}