export interface Component {
    readonly id: string,
    name: string,
    j1: string,
    k1: string,
    k2: string,
    l2: string,
    m1: string,
    m2: string,
    n2: string,
    o1: string,
    p1: string,
    q1: string,
    s1: string,
    s2: string,
    t2: string,
    v2: string,
    type: string,
    velocity: string,
}